name: Build and test projects

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build-test-dotnet:
    runs-on: ubuntu-latest
    name: Build and test dotnet solution
    env:
      DOTNET_NOLOGO: true
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.100'
      - run: dotnet build
      - run: dotnet test
  build-test-client:
    runs-on: ubuntu-latest
    name: Build and test client app
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run: npm install
        working-directory: ./src/WebApp
      - run: npm run build
        working-directory: ./src/WebApp
      - run: npm run test
        working-directory: ./src/WebApp
