name: Build and test dotnet solution

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and test dotnet solution
    env:
      DOTNET_NOLOGO: true
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.100'
      - run: dotnet build
      - run: dotnet test
