name: Build and test projects

on: [push, pull_request]

jobs:
  build-test-dotnet:
    runs-on: ubuntu-latest
    name: Build and test dotnet solution
    env:
      DOTNET_NOLOGO: true
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.100'
      - run: dotnet build
      - run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          flags: dotnet
  build-test-client:
    runs-on: ubuntu-latest
    name: Build and test client app
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run: npm install
        working-directory: ./src/WebApp
      - run: npm run build
        working-directory: ./src/WebApp
      - run: npm run coverage
        working-directory: ./src/WebApp
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          flags: webapp
